### ISSUE TITLE
error when compiling a template

### ISSUE THREAD

**Issue by diecamdia** [pipobscure/pistachio#1]
when i try to complile with the comamnd line:

  pistachio --out=splash-tpl.js splash-tpl.html i get the error:

bash: /usr/bin/pistachio: /usr/local/bin/node: intérprete erróneo: No existe el archivo o el directorio

bash: /usr/bin/pistachio: /usr/local/bin/node: bad interpreter: No such file or directory

when i execute de command pistachio -v i get the same error.

I am working in Ubuntu 13.04
nodejs versión v0.10.20
npm versión 1.3.11

thanks,

**Comment by pipobscure** [comment]
run it as:

    node /usr/bin/pistachio ...

instead. This is because your nodejs is not installed in the default path.
